"""init

Revision ID: 58366c45a89b
Revises: 
Create Date: 2026-02-24 00:38:15.313920

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '58366c45a89b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    tables = set(inspector.get_table_names())

    if 'matches' not in tables:
        op.create_table(
            'matches',
            sa.Column('id', sa.String(), nullable=False),
            sa.Column('home_team', sa.String(), nullable=True),
            sa.Column('away_team', sa.String(), nullable=True),
            sa.Column('match_date', sa.String(), nullable=True),
            sa.Column('event_data_path', sa.String(), nullable=True),
            sa.Column('video_path', sa.String(), nullable=True),
            sa.Column('status', sa.String(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )

    created_events = False
    if 'events' not in tables:
        op.create_table(
            'events',
            sa.Column('id', sa.String(), nullable=False),
            sa.Column('match_id', sa.String(), nullable=False),
            sa.Column('timestamp', sa.Float(), nullable=True),
            sa.Column('type', sa.String(), nullable=False),
            sa.Column('team', sa.String(), nullable=True),
            sa.Column('player_id', sa.String(), nullable=True),
            sa.Column('x', sa.Float(), nullable=True),
            sa.Column('y', sa.Float(), nullable=True),
            sa.Column('payload', sa.JSON(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        created_events = True

    if 'events' in tables or created_events:
        existing_indexes = {idx['name'] for idx in inspector.get_indexes('events')}
        if 'ix_events_created_at' not in existing_indexes:
            op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
        if 'ix_events_match_created' not in existing_indexes:
            op.create_index('ix_events_match_created', 'events', ['match_id', 'created_at'], unique=False)
        if 'ix_events_match_id' not in existing_indexes:
            op.create_index(op.f('ix_events_match_id'), 'events', ['match_id'], unique=False)

    if 'insights' not in tables:
        op.create_table(
            'insights',
            sa.Column('id', sa.String(), nullable=False),
            sa.Column('match_id', sa.String(), nullable=True),
            sa.Column('type', sa.String(), nullable=False),
            sa.Column('description', sa.Text(), nullable=False),
            sa.Column('severity', sa.String(), nullable=True),
            sa.Column('data', sa.JSON(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
            sa.PrimaryKeyConstraint('id')
        )

    created_live = False
    if 'live_snapshots' not in tables:
        op.create_table(
            'live_snapshots',
            sa.Column('id', sa.String(), nullable=False),
            sa.Column('match_id', sa.String(), nullable=False),
            sa.Column('payload', sa.JSON(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('match_id')
        )
        created_live = True

    if 'live_snapshots' in tables or created_live:
        existing_live_indexes = {idx['name'] for idx in inspector.get_indexes('live_snapshots')}
        if 'ix_live_snapshots_updated_at' not in existing_live_indexes:
            op.create_index(op.f('ix_live_snapshots_updated_at'), 'live_snapshots', ['updated_at'], unique=False)

    if 'players' not in tables:
        op.create_table(
            'players',
            sa.Column('id', sa.String(), nullable=False),
            sa.Column('external_id', sa.String(), nullable=True),
            sa.Column('name', sa.String(), nullable=False),
            sa.Column('team', sa.String(), nullable=True),
            sa.Column('position', sa.String(), nullable=True),
            sa.Column('metrics', sa.JSON(), nullable=True),
            sa.Column('match_id', sa.String(), nullable=True),
            sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    op.drop_index(op.f('ix_live_snapshots_updated_at'), table_name='live_snapshots')
    op.drop_table('live_snapshots')
    op.drop_table('insights')
    op.drop_index(op.f('ix_events_match_id'), table_name='events')
    op.drop_index('ix_events_match_created', table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_table('events')
    op.drop_table('matches')
    # ### end Alembic commands ###
