"""init

Revision ID: 58366c45a89b
Revises: 
Create Date: 2026-02-24 00:38:15.313920

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '58366c45a89b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    tables = set(inspector.get_table_names())
    dialect = bind.dialect.name

    def column_names(table_name: str) -> set[str]:
        return {col["name"] for col in inspector.get_columns(table_name)} if table_name in tables else set()

    def unique_on(table_name: str, columns: list[str]) -> bool:
        if table_name not in tables:
            return False
        target = set(columns)
        for constraint in inspector.get_unique_constraints(table_name):
            if set(constraint.get("column_names") or []) == target:
                return True
        return False

    if 'matches' not in tables:
        op.create_table(
            'matches',
            sa.Column('id', sa.String(), nullable=False),
            sa.Column('home_team', sa.String(), nullable=True),
            sa.Column('away_team', sa.String(), nullable=True),
            sa.Column('match_date', sa.String(), nullable=True),
            sa.Column('event_data_path', sa.String(), nullable=True),
            sa.Column('video_path', sa.String(), nullable=True),
            sa.Column('status', sa.String(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
    else:
        cols = column_names('matches')
        if 'home_team' not in cols:
            op.add_column('matches', sa.Column('home_team', sa.String(), nullable=True))
        if 'away_team' not in cols:
            op.add_column('matches', sa.Column('away_team', sa.String(), nullable=True))
        if 'match_date' not in cols:
            op.add_column('matches', sa.Column('match_date', sa.String(), nullable=True))
        if 'event_data_path' not in cols:
            op.add_column('matches', sa.Column('event_data_path', sa.String(), nullable=True))
        if 'video_path' not in cols:
            op.add_column('matches', sa.Column('video_path', sa.String(), nullable=True))
        if 'status' not in cols:
            op.add_column('matches', sa.Column('status', sa.String(), nullable=True))
        if 'created_at' not in cols:
            op.add_column('matches', sa.Column('created_at', sa.DateTime(), nullable=True))

    created_events = False
    if 'events' not in tables:
        op.create_table(
            'events',
            sa.Column('id', sa.String(), nullable=False),
            sa.Column('match_id', sa.String(), nullable=False),
            sa.Column('timestamp', sa.Float(), nullable=True),
            sa.Column('type', sa.String(), nullable=False),
            sa.Column('team', sa.String(), nullable=True),
            sa.Column('player_id', sa.String(), nullable=True),
            sa.Column('x', sa.Float(), nullable=True),
            sa.Column('y', sa.Float(), nullable=True),
            sa.Column('payload', sa.JSON(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        created_events = True
    else:
        cols = column_names('events')
        if 'match_id' not in cols:
            op.add_column('events', sa.Column('match_id', sa.String(), nullable=False))
        if 'timestamp' not in cols:
            op.add_column('events', sa.Column('timestamp', sa.Float(), nullable=True))
        if 'type' not in cols:
            op.add_column('events', sa.Column('type', sa.String(), nullable=False))
        if 'team' not in cols:
            op.add_column('events', sa.Column('team', sa.String(), nullable=True))
        if 'player_id' not in cols:
            op.add_column('events', sa.Column('player_id', sa.String(), nullable=True))
        if 'x' not in cols:
            op.add_column('events', sa.Column('x', sa.Float(), nullable=True))
        if 'y' not in cols:
            op.add_column('events', sa.Column('y', sa.Float(), nullable=True))
        if 'payload' not in cols:
            op.add_column('events', sa.Column('payload', sa.JSON(), nullable=True))
        if 'created_at' not in cols:
            op.add_column('events', sa.Column('created_at', sa.DateTime(), nullable=True))

    if 'events' in tables or created_events:
        existing_indexes = {idx['name'] for idx in inspector.get_indexes('events')}
        if 'ix_events_created_at' not in existing_indexes:
            op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
        if 'ix_events_match_created' not in existing_indexes:
            op.create_index('ix_events_match_created', 'events', ['match_id', 'created_at'], unique=False)
        if 'ix_events_match_id' not in existing_indexes:
            op.create_index(op.f('ix_events_match_id'), 'events', ['match_id'], unique=False)

    if 'insights' not in tables:
        op.create_table(
            'insights',
            sa.Column('id', sa.String(), nullable=False),
            sa.Column('match_id', sa.String(), nullable=True),
            sa.Column('type', sa.String(), nullable=False),
            sa.Column('description', sa.Text(), nullable=False),
            sa.Column('severity', sa.String(), nullable=True),
            sa.Column('data', sa.JSON(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    else:
        cols = column_names('insights')
        if 'match_id' not in cols:
            op.add_column('insights', sa.Column('match_id', sa.String(), nullable=True))
        if 'type' not in cols:
            op.add_column('insights', sa.Column('type', sa.String(), nullable=False))
        if 'description' not in cols:
            op.add_column('insights', sa.Column('description', sa.Text(), nullable=False))
        if 'severity' not in cols:
            op.add_column('insights', sa.Column('severity', sa.String(), nullable=True))
        if 'data' not in cols:
            op.add_column('insights', sa.Column('data', sa.JSON(), nullable=True))
        if 'created_at' not in cols:
            op.add_column('insights', sa.Column('created_at', sa.DateTime(), nullable=True))

    created_live = False
    if 'live_snapshots' not in tables:
        op.create_table(
            'live_snapshots',
            sa.Column('id', sa.String(), nullable=False),
            sa.Column('match_id', sa.String(), nullable=False),
            sa.Column('payload', sa.JSON(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('match_id')
        )
        created_live = True
    else:
        cols = column_names('live_snapshots')
        if 'match_id' not in cols:
            op.add_column('live_snapshots', sa.Column('match_id', sa.String(), nullable=False))
        if 'payload' not in cols:
            op.add_column('live_snapshots', sa.Column('payload', sa.JSON(), nullable=False))
        if 'updated_at' not in cols:
            op.add_column('live_snapshots', sa.Column('updated_at', sa.DateTime(), nullable=True))
        if not unique_on('live_snapshots', ['match_id']):
            op.create_unique_constraint('uq_live_snapshots_match_id', 'live_snapshots', ['match_id'])

    if 'live_snapshots' in tables or created_live:
        existing_live_indexes = {idx['name'] for idx in inspector.get_indexes('live_snapshots')}
        if 'ix_live_snapshots_updated_at' not in existing_live_indexes:
            op.create_index(op.f('ix_live_snapshots_updated_at'), 'live_snapshots', ['updated_at'], unique=False)

    if 'players' not in tables:
        op.create_table(
            'players',
            sa.Column('id', sa.String(), nullable=False),
            sa.Column('external_id', sa.String(), nullable=True),
            sa.Column('name', sa.String(), nullable=False),
            sa.Column('team', sa.String(), nullable=True),
            sa.Column('position', sa.String(), nullable=True),
            sa.Column('metrics', sa.JSON(), nullable=True),
            sa.Column('match_id', sa.String(), nullable=True),
            sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    else:
        cols = column_names('players')
        if 'external_id' not in cols:
            op.add_column('players', sa.Column('external_id', sa.String(), nullable=True))
        if 'name' not in cols:
            op.add_column('players', sa.Column('name', sa.String(), nullable=False))
        if 'team' not in cols:
            op.add_column('players', sa.Column('team', sa.String(), nullable=True))
        if 'position' not in cols:
            op.add_column('players', sa.Column('position', sa.String(), nullable=True))
        if 'metrics' not in cols:
            op.add_column('players', sa.Column('metrics', sa.JSON(), nullable=True))
        if 'match_id' not in cols:
            op.add_column('players', sa.Column('match_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    op.drop_index(op.f('ix_live_snapshots_updated_at'), table_name='live_snapshots')
    op.drop_table('live_snapshots')
    op.drop_table('insights')
    op.drop_index(op.f('ix_events_match_id'), table_name='events')
    op.drop_index('ix_events_match_created', table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_table('events')
    op.drop_table('matches')
    # ### end Alembic commands ###
